# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamResponseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('word_list', models.CharField(max_length=5000)),
                ('responder_count', models.IntegerField()),
                ('team_name', models.CharField(max_length=64, null=True)),
                ('archive_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTemperature',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('password', models.CharField(max_length=256)),
                ('archive_schedule', models.IntegerField(default=0)),
                ('archive_date', models.DateTimeField(null=True)),
                ('survey_type', models.CharField(default=b'TEAMTEMP', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('word', models.CharField(max_length=32)),
                ('team_name', models.CharField(max_length=64, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(null=True)),
                ('archive_date', models.DateTimeField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.TeamTemperature')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordCloudImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('word_list', models.CharField(max_length=5000)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='temperatureresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.User'),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.User'),
        ),
        migrations.AddField(
            model_name='teams',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.TeamTemperature'),
        ),
        migrations.AddField(
            model_name='teamresponsehistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.TeamTemperature'),
        ),
    ]
