# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='dept_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='region_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='site_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='default_tz',
            field=models.CharField(default=b'Australia/Queensland', max_length=64),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='dept_names',
            field=models.CharField(default=b'DEPT,DEPT2', max_length=64),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='max_word_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='region_names',
            field=models.CharField(default=b'REGION,REGION2', max_length=64),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='site_names',
            field=models.CharField(default=b'SITE,SITE2', max_length=64),
        ),
    ]
