# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_auto_20160614_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamresponsehistory',
            options={'verbose_name_plural': 'Team response histories'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='teamresponsehistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_response_histories', to='responses.TeamTemperature'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='responses.TeamTemperature'),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_temperatures', to='responses.User'),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_responses', to='responses.TeamTemperature'),
        ),
    ]
