# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_auto_20160617_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamresponsehistory',
            name='team_name',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='archive_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='team_name',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wordcloudimage',
            name='word_list',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together=set([('request', 'team_name')]),
        ),
    ]
