# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 01:35
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F, Func

def lowercase_word_cloud_image_word_list(apps, schema_editor):
    WordCloudImage = apps.get_model('responses', 'WordCloudImage')
    WordCloudImage.objects.annotate(
        word_list_lower=Func(F('word_list'), function='LOWER')
    ).all().update(word_list=F('word_list_lower'))

def lowercase_team_response_history_word_list(apps, schema_editor):
    TeamResponseHistory = apps.get_model('responses', 'TeamResponseHistory')
    TeamResponseHistory.objects.annotate(
        word_list_lower=Func(F('word_list'), function='LOWER')
    ).all().update(word_list=F('word_list_lower'))

def lowercase_temperature_response_word(apps, schema_editor):
    TemperatureResponse = apps.get_model('responses', 'TemperatureResponse')
    TemperatureResponse.objects.annotate(
        word_lower=Func(F('word'), function='LOWER')
    ).all().update(word=F('word_lower'))

class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_auto_20160617_1324'),
    ]

    operations = [
        migrations.RunPython(lowercase_word_cloud_image_word_list),
        migrations.RunPython(lowercase_team_response_history_word_list),
        migrations.RunPython(lowercase_temperature_response_word),
    ]
