# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0005_lowercase_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_responses', to='responses.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
