# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0006_auto_20161212_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloudimage',
            name='word_hash',
            field=models.CharField(db_index=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
