# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0007_wordcloudimage_word_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='teams',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamtemperature',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamresponsehistory',
            name='archive_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dept_name',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='region_name',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='site_name',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='survey_type',
            field=models.CharField(choices=[(b'TEAMTEMP', b'Team Temperature'), (b'DEPT-REGION-SITE', b'Department-Region-Site Temperature'), (b'CUSTOMERFEEDBACK', b'Customer Feedback')], db_index=True, default=b'TEAMTEMP', max_length=20),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='response_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordcloudimage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
