# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0008_auto_20161216_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtemperature',
            name='dept_names',
            field=models.CharField(blank=True, default=b'DEPT,DEPT2', max_length=64),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='region_names',
            field=models.CharField(blank=True, default=b'REGION,REGION2', max_length=64),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='site_names',
            field=models.CharField(blank=True, default=b'SITE,SITE2', max_length=64),
        ),
    ]
