# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0010_auto_20161221_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamresponsehistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dept_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='region_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='site_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='dept_names',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='region_names',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='site_names',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='archive_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='response_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='team_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='wordcloudimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
