# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0011_auto_20170111_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtemperature',
            name='next_archive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
