# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0011_auto_20170111_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperatureresponse',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterUniqueTogether(
            name='temperatureresponse',
            unique_together=set([('request', 'responder', 'team_name', 'archive_date')]),
        ),
    ]
