# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0012_teamtemperature_next_archive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamresponsehistory',
            name='responder_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='archive_schedule',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamtemperature',
            name='max_word_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
