# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 06:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0014_auto_20170130_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureresponse',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
