# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0016_auto_20170220_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloudimage',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
