# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 06:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0017_auto_20170301_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamresponsehistory',
            name='maximum_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='teamresponsehistory',
            name='minimum_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
