# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0019_auto_20170710_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtemperature',
            name='max_word_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='word',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
