# Generated by Django 2.0 on 2017-12-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0020_auto_20170927_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtemperature',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_temperatures', to='responses.User'),
        ),
        migrations.AlterField(
            model_name='temperatureresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='temperature_responses', to='responses.User'),
        ),
    ]
