# Generated by Django 2.2.12 on 2020-05-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0025_auto_20200429_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloudimage',
            name='height',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='wordcloudimage',
            name='width',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='wordcloudimage',
            name='word_hash',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='wordcloudimage',
            unique_together={('word_hash', 'width', 'height')},
        ),
    ]
