# Generated by Django 2.2.12 on 2020-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0026_auto_20200513_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloudimage',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wordcloudimage',
            name='width',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
