# Generated by Django 2.2.12 on 2020-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0027_auto_20200513_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloudimage',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordcloudimage',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
